spring:
  datasource:
    url: jdbc:h2:~/codereview;AUTO_SERVER=TRUE
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: exampleJwtKeyexampleJwtKeyexampleJwtKeyexampleJwtKeyexampleJwtKeyexampleJwtKe
  expiration: 86400000
  issuer: codereviewstudy
